/* 
 * Scopevisio OpenScope REST API
 *
 * <p>This is an interactive API reference for the Scopevisio REST API.</p><p>Below you will see the main sections of the API. Click each section in order to see the endpoints that are available in that category and use the 'Try it out' button to make API calls.</p><p>For endpoints that require authentication you can click the lock symbol in the top right of the endpoint description, which will take you to a login form.</p><h3>Authentication</h3><p>In order to use the \"Try it out\" function in Swagger you need your own Scopevisio account. If you have not set up a Scopevisio user account already you can do so <a href='https://www.scopevisio.com' target='_blank'>here</a>.</p><h3>Example Application</h3><p>We also have an example application you can reach <a href='../browser/index.html'> here </a>. Usage requires a Scopevisio account.</p><h3>Search Documentation</h3><p>Our documentation regarding <a href='../browser/index.html#!/searchscope'>search specification and paging  </a>.</p><h3>General Documentation</h3><p>Our general documentation can be found <a href='../browser/index.html#!/documentation'> here </a>.</p>
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@scopevisio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using CompuMaster.Scopevisio.OpenApi.Client;
using CompuMaster.Scopevisio.OpenApi.Api;
using CompuMaster.Scopevisio.OpenApi.Model;

namespace CompuMaster.Scopevisio.OpenApi.Test
{
    /// <summary>
    ///  Class for testing IncomingInvoiceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class IncomingInvoiceApiTests
    {
        private IncomingInvoiceApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new IncomingInvoiceApi(new TestConfig());
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IncomingInvoiceApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' IncomingInvoiceApi
            //Assert.IsInstanceOf(typeof(IncomingInvoiceApi), instance);
        }

        
        /// <summary>
        /// Test CreateIncomingInvoice
        /// </summary>
        [Test]
        public void CreateIncomingInvoiceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //IncomingInvoiceForm body = null;
            //instance.CreateIncomingInvoice(body);
            
        }
        
        /// <summary>
        /// Test GetIncomingInvoiceTeamworkFileLink
        /// </summary>
        [Test]
        public void GetIncomingInvoiceTeamworkFileLinkTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string idOrNumber = null;
            //instance.GetIncomingInvoiceTeamworkFileLink(idOrNumber);
            
        }
        
        /// <summary>
        /// Test GetIncomingInvoices
        /// </summary>
        [Test]
        public void GetIncomingInvoicesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string body = null;
            //instance.GetIncomingInvoices(body);
            
        }
        
        /// <summary>
        /// Test GetInvoice
        /// </summary>
        [Test]
        public void GetInvoiceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string idOrNumber = null;
            //string fields = null;
            //instance.GetInvoice(idOrNumber, fields);
            
        }
        
        /// <summary>
        /// Test GetInvoiceFile
        /// </summary>
        [Test]
        public void GetInvoiceFileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string idOrNumber = null;
            //instance.GetInvoiceFile(idOrNumber);
            
        }
        
    }

}
