/* 
 * Scopevisio OpenScope REST API
 *
 * <p>This is an interactive API reference for the Scopevisio REST API.</p><p>Below you will see the main sections of the API. Click each section in order to see the endpoints that are available in that category and use the 'Try it out' button to make API calls.</p><p>For endpoints that require authentication you can click the lock symbol in the top right of the endpoint description, which will take you to a login form.</p><h3>Authentication</h3><p>In order to use the \"Try it out\" function in Swagger you need your own Scopevisio account. If you have not set up a Scopevisio user account already you can do so <a href='https://www.scopevisio.com' target='_blank'>here</a>.</p><h3>Example Application</h3><p>We also have an example application you can reach <a href='../browser/index.html'> here </a>. Usage requires a Scopevisio account.</p><h3>Search Documentation</h3><p>Our documentation regarding <a href='../browser/index.html#!/searchscope'>search specification and paging  </a>.</p><h3>General Documentation</h3><p>Our general documentation can be found <a href='../browser/index.html#!/documentation'> here </a>.</p>
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@scopevisio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = CompuMaster.Scopevisio.OpenApi.Client.OpenAPIDateConverter;

namespace CompuMaster.Scopevisio.OpenApi.Model
{
    /// <summary>
    /// CustomField
    /// </summary>
    [DataContract]
    public partial class CustomField :  IEquatable<CustomField>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomField" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CustomField() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomField" /> class.
        /// </summary>
        /// <param name="customFieldName">See our &lt;a href&#x3D;&#39;../browser/index.html#!/documentation#cf&#39;&gt;documentation &lt;/a&gt; for how the names are put together. (required).</param>
        /// <param name="customFieldValue">customFieldValue (required).</param>
        public CustomField(string customFieldName = default(string), Object customFieldValue = default(Object))
        {
            // to ensure "customFieldName" is required (not null)
            if (customFieldName == null)
            {
                throw new InvalidDataException("customFieldName is a required property for CustomField and cannot be null");
            }
            else
            {
                this.CustomFieldName = customFieldName;
            }
            
            // to ensure "customFieldValue" is required (not null)
            if (customFieldValue == null)
            {
                throw new InvalidDataException("customFieldValue is a required property for CustomField and cannot be null");
            }
            else
            {
                this.CustomFieldValue = customFieldValue;
            }
            
        }
        
        /// <summary>
        /// See our &lt;a href&#x3D;&#39;../browser/index.html#!/documentation#cf&#39;&gt;documentation &lt;/a&gt; for how the names are put together.
        /// </summary>
        /// <value>See our &lt;a href&#x3D;&#39;../browser/index.html#!/documentation#cf&#39;&gt;documentation &lt;/a&gt; for how the names are put together.</value>
        [DataMember(Name="customFieldName", EmitDefaultValue=false)]
        public string CustomFieldName { get; set; }

        /// <summary>
        /// Gets or Sets CustomFieldValue
        /// </summary>
        [DataMember(Name="customFieldValue", EmitDefaultValue=false)]
        public Object CustomFieldValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CustomField {\n");
            sb.Append("  CustomFieldName: ").Append(CustomFieldName).Append("\n");
            sb.Append("  CustomFieldValue: ").Append(CustomFieldValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CustomField);
        }

        /// <summary>
        /// Returns true if CustomField instances are equal
        /// </summary>
        /// <param name="input">Instance of CustomField to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CustomField input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CustomFieldName == input.CustomFieldName ||
                    (this.CustomFieldName != null &&
                    this.CustomFieldName.Equals(input.CustomFieldName))
                ) && 
                (
                    this.CustomFieldValue == input.CustomFieldValue ||
                    (this.CustomFieldValue != null &&
                    this.CustomFieldValue.Equals(input.CustomFieldValue))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CustomFieldName != null)
                    hashCode = hashCode * 59 + this.CustomFieldName.GetHashCode();
                if (this.CustomFieldValue != null)
                    hashCode = hashCode * 59 + this.CustomFieldValue.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
