/* 
 * Scopevisio OpenScope REST API
 *
 * <p>This is an interactive API reference for the Scopevisio REST API.</p><p>Below you will see the main sections of the API. Click each section in order to see the endpoints that are available in that category and use the 'Try it out' button to make API calls.</p><p>For endpoints that require authentication you can click the lock symbol in the top right of the endpoint description, which will take you to a login form.</p><h3>Authentication</h3><p>In order to use the \"Try it out\" function in Swagger you need your own Scopevisio account. If you have not set up a Scopevisio user account already you can do so <a href='https://www.scopevisio.com' target='_blank'>here</a>.</p><h3>Example Application</h3><p>We also have an example application you can reach <a href='../browser/index.html'> here </a>. Usage requires a Scopevisio account.</p><h3>Search Documentation</h3><p>Our documentation regarding <a href='../browser/index.html#!/searchscope'>search specification and paging  </a>.</p><h3>General Documentation</h3><p>Our general documentation can be found <a href='../browser/index.html#!/documentation'> here </a>.</p>
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@scopevisio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = CompuMaster.Scopevisio.OpenApi.Client.OpenAPIDateConverter;

namespace CompuMaster.Scopevisio.OpenApi.Model
{
    /// <summary>
    /// OutgoingInvoiceImportResult
    /// </summary>
    [DataContract]
    public partial class OutgoingInvoiceImportResult :  IEquatable<OutgoingInvoiceImportResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OutgoingInvoiceImportResult" /> class.
        /// </summary>
        /// <param name="message">message.</param>
        /// <param name="invoices">invoices.</param>
        /// <param name="customers">customers.</param>
        /// <param name="vendors">vendors.</param>
        public OutgoingInvoiceImportResult(string message = default(string), List<OutgoingInvoice> invoices = default(List<OutgoingInvoice>), List<Account> customers = default(List<Account>), List<Account> vendors = default(List<Account>))
        {
            this.Message = message;
            this.Invoices = invoices;
            this.Customers = customers;
            this.Vendors = vendors;
        }
        
        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name="message", EmitDefaultValue=false)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets Invoices
        /// </summary>
        [DataMember(Name="invoices", EmitDefaultValue=false)]
        public List<OutgoingInvoice> Invoices { get; set; }

        /// <summary>
        /// Gets or Sets Customers
        /// </summary>
        [DataMember(Name="customers", EmitDefaultValue=false)]
        public List<Account> Customers { get; set; }

        /// <summary>
        /// Gets or Sets Vendors
        /// </summary>
        [DataMember(Name="vendors", EmitDefaultValue=false)]
        public List<Account> Vendors { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OutgoingInvoiceImportResult {\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Invoices: ").Append(Invoices).Append("\n");
            sb.Append("  Customers: ").Append(Customers).Append("\n");
            sb.Append("  Vendors: ").Append(Vendors).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OutgoingInvoiceImportResult);
        }

        /// <summary>
        /// Returns true if OutgoingInvoiceImportResult instances are equal
        /// </summary>
        /// <param name="input">Instance of OutgoingInvoiceImportResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OutgoingInvoiceImportResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                ) && 
                (
                    this.Invoices == input.Invoices ||
                    this.Invoices != null &&
                    input.Invoices != null &&
                    this.Invoices.SequenceEqual(input.Invoices)
                ) && 
                (
                    this.Customers == input.Customers ||
                    this.Customers != null &&
                    input.Customers != null &&
                    this.Customers.SequenceEqual(input.Customers)
                ) && 
                (
                    this.Vendors == input.Vendors ||
                    this.Vendors != null &&
                    input.Vendors != null &&
                    this.Vendors.SequenceEqual(input.Vendors)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Message != null)
                    hashCode = hashCode * 59 + this.Message.GetHashCode();
                if (this.Invoices != null)
                    hashCode = hashCode * 59 + this.Invoices.GetHashCode();
                if (this.Customers != null)
                    hashCode = hashCode * 59 + this.Customers.GetHashCode();
                if (this.Vendors != null)
                    hashCode = hashCode * 59 + this.Vendors.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
