/* 
 * Scopevisio OpenScope REST API
 *
 * <p>This is an interactive API reference for the Scopevisio REST API.</p><p>Below you will see the main sections of the API. Click each section in order to see the endpoints that are available in that category and use the 'Try it out' button to make API calls.</p><p>For endpoints that require authentication you can click the lock symbol in the top right of the endpoint description, which will take you to a login form.</p><h3>Authentication</h3><p>In order to use the \"Try it out\" function in Swagger you need your own Scopevisio account. If you have not set up a Scopevisio user account already you can do so <a href='https://www.scopevisio.com' target='_blank'>here</a>.</p><h3>Example Application</h3><p>We also have an example application you can reach <a href='../browser/index.html'> here </a>. Usage requires a Scopevisio account.</p><h3>Search Documentation</h3><p>Our documentation regarding <a href='../browser/index.html#!/searchscope'>search specification and paging  </a>.</p><h3>General Documentation</h3><p>Our general documentation can be found <a href='../browser/index.html#!/documentation'> here </a>.</p>
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@scopevisio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CompuMaster.Scopevisio.OpenApi.Api;
using CompuMaster.Scopevisio.OpenApi.Model;
using CompuMaster.Scopevisio.OpenApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CompuMaster.Scopevisio.OpenApi.Test
{
    /// <summary>
    ///  Class for testing OutgoingInvoicePositionForm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OutgoingInvoicePositionFormTests
    {
        // TODO uncomment below to declare an instance variable for OutgoingInvoicePositionForm
        //private OutgoingInvoicePositionForm instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OutgoingInvoicePositionForm
            //instance = new OutgoingInvoicePositionForm();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OutgoingInvoicePositionForm
        /// </summary>
        [Test]
        public void OutgoingInvoicePositionFormInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" OutgoingInvoicePositionForm
            //Assert.IsInstanceOf(typeof(OutgoingInvoicePositionForm), instance);
        }


        /// <summary>
        /// Test the property 'TypeDisplay'
        /// </summary>
        [Test]
        public void TypeDisplayTest()
        {
            // TODO unit test for the property 'TypeDisplay'
        }
        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Test]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Test]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }
        /// <summary>
        /// Test the property 'SingleAmount'
        /// </summary>
        [Test]
        public void SingleAmountTest()
        {
            // TODO unit test for the property 'SingleAmount'
        }
        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Test]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }
        /// <summary>
        /// Test the property 'VatKey'
        /// </summary>
        [Test]
        public void VatKeyTest()
        {
            // TODO unit test for the property 'VatKey'
        }
        /// <summary>
        /// Test the property 'Discount'
        /// </summary>
        [Test]
        public void DiscountTest()
        {
            // TODO unit test for the property 'Discount'
        }
        /// <summary>
        /// Test the property 'FreeText1'
        /// </summary>
        [Test]
        public void FreeText1Test()
        {
            // TODO unit test for the property 'FreeText1'
        }
        /// <summary>
        /// Test the property 'FreeText2'
        /// </summary>
        [Test]
        public void FreeText2Test()
        {
            // TODO unit test for the property 'FreeText2'
        }
        /// <summary>
        /// Test the property 'SingleCostAmount'
        /// </summary>
        [Test]
        public void SingleCostAmountTest()
        {
            // TODO unit test for the property 'SingleCostAmount'
        }
        /// <summary>
        /// Test the property 'ValutaDate'
        /// </summary>
        [Test]
        public void ValutaDateTest()
        {
            // TODO unit test for the property 'ValutaDate'
        }
        /// <summary>
        /// Test the property 'AsIfSold'
        /// </summary>
        [Test]
        public void AsIfSoldTest()
        {
            // TODO unit test for the property 'AsIfSold'
        }

    }

}
