/* 
 * Scopevisio OpenScope REST API
 *
 * <p>This is an interactive API reference for the Scopevisio REST API.</p><p>Below you will see the main sections of the API. Click each section in order to see the endpoints that are available in that category and use the 'Try it out' button to make API calls.</p><p>For endpoints that require authentication you can click the lock symbol in the top right of the endpoint description, which will take you to a login form.</p><h3>Authentication</h3><p>In order to use the \"Try it out\" function in Swagger you need your own Scopevisio account. If you have not set up a Scopevisio user account already you can do so <a href='https://www.scopevisio.com' target='_blank'>here</a>.</p><h3>Example Application</h3><p>We also have an example application you can reach <a href='../browser/index.html'> here </a>. Usage requires a Scopevisio account.</p><h3>Search Documentation</h3><p>Our documentation regarding <a href='../browser/index.html#!/searchscope'>search specification and paging  </a>.</p><h3>General Documentation</h3><p>Our general documentation can be found <a href='../browser/index.html#!/documentation'> here </a>.</p>
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@scopevisio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CompuMaster.Scopevisio.OpenApi.Api;
using CompuMaster.Scopevisio.OpenApi.Model;
using CompuMaster.Scopevisio.OpenApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CompuMaster.Scopevisio.OpenApi.Test
{
    /// <summary>
    ///  Class for testing ImpersonalAccountRow
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ImpersonalAccountRowTests
    {
        // TODO uncomment below to declare an instance variable for ImpersonalAccountRow
        //private ImpersonalAccountRow instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ImpersonalAccountRow
            //instance = new ImpersonalAccountRow();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ImpersonalAccountRow
        /// </summary>
        [Test]
        public void ImpersonalAccountRowInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ImpersonalAccountRow
            //Assert.IsInstanceOf(typeof(ImpersonalAccountRow), instance);
        }


        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Test]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'VatCode'
        /// </summary>
        [Test]
        public void VatCodeTest()
        {
            // TODO unit test for the property 'VatCode'
        }
        /// <summary>
        /// Test the property 'VatKey'
        /// </summary>
        [Test]
        public void VatKeyTest()
        {
            // TODO unit test for the property 'VatKey'
        }
        /// <summary>
        /// Test the property 'FixVatKey'
        /// </summary>
        [Test]
        public void FixVatKeyTest()
        {
            // TODO unit test for the property 'FixVatKey'
        }
        /// <summary>
        /// Test the property 'Deactivated'
        /// </summary>
        [Test]
        public void DeactivatedTest()
        {
            // TODO unit test for the property 'Deactivated'
        }
        /// <summary>
        /// Test the property 'DirectPosting'
        /// </summary>
        [Test]
        public void DirectPostingTest()
        {
            // TODO unit test for the property 'DirectPosting'
        }
        /// <summary>
        /// Test the property 'DiscountAccount'
        /// </summary>
        [Test]
        public void DiscountAccountTest()
        {
            // TODO unit test for the property 'DiscountAccount'
        }
        /// <summary>
        /// Test the property 'IsFinanceAccount'
        /// </summary>
        [Test]
        public void IsFinanceAccountTest()
        {
            // TODO unit test for the property 'IsFinanceAccount'
        }
        /// <summary>
        /// Test the property 'SubjectToClearing'
        /// </summary>
        [Test]
        public void SubjectToClearingTest()
        {
            // TODO unit test for the property 'SubjectToClearing'
        }
        /// <summary>
        /// Test the property 'Dimensions'
        /// </summary>
        [Test]
        public void DimensionsTest()
        {
            // TODO unit test for the property 'Dimensions'
        }

    }

}
