/* 
 * Scopevisio OpenScope REST API
 *
 * <p>This is an interactive API reference for the Scopevisio REST API.</p><p>Below you will see the main sections of the API. Click each section in order to see the endpoints that are available in that category and use the 'Try it out' button to make API calls.</p><p>For endpoints that require authentication you can click the lock symbol in the top right of the endpoint description, which will take you to a login form.</p><h3>Authentication</h3><p>In order to use the \"Try it out\" function in Swagger you need your own Scopevisio account. If you have not set up a Scopevisio user account already you can do so <a href='https://www.scopevisio.com' target='_blank'>here</a>.</p><h3>Example Application</h3><p>We also have an example application you can reach <a href='../browser/index.html'> here </a>. Usage requires a Scopevisio account.</p><h3>Search Documentation</h3><p>Our documentation regarding <a href='../browser/index.html#!/searchscope'>search specification and paging  </a>.</p><h3>General Documentation</h3><p>Our general documentation can be found <a href='../browser/index.html#!/documentation'> here </a>.</p>
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@scopevisio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CompuMaster.Scopevisio.OpenApi.Api;
using CompuMaster.Scopevisio.OpenApi.Model;
using CompuMaster.Scopevisio.OpenApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CompuMaster.Scopevisio.OpenApi.Test
{
    /// <summary>
    ///  Class for testing KontaktForm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KontaktFormTests
    {
        // TODO uncomment below to declare an instance variable for KontaktForm
        //private KontaktForm instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of KontaktForm
            //instance = new KontaktForm();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of KontaktForm
        /// </summary>
        [Test]
        public void KontaktFormInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" KontaktForm
            //Assert.IsInstanceOf(typeof(KontaktForm), instance);
        }


        /// <summary>
        /// Test the property 'Person'
        /// </summary>
        [Test]
        public void PersonTest()
        {
            // TODO unit test for the property 'Person'
        }
        /// <summary>
        /// Test the property 'Salutation'
        /// </summary>
        [Test]
        public void SalutationTest()
        {
            // TODO unit test for the property 'Salutation'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Lastname'
        /// </summary>
        [Test]
        public void LastnameTest()
        {
            // TODO unit test for the property 'Lastname'
        }
        /// <summary>
        /// Test the property 'Firstname'
        /// </summary>
        [Test]
        public void FirstnameTest()
        {
            // TODO unit test for the property 'Firstname'
        }
        /// <summary>
        /// Test the property 'PaymentTypeName'
        /// </summary>
        [Test]
        public void PaymentTypeNameTest()
        {
            // TODO unit test for the property 'PaymentTypeName'
        }
        /// <summary>
        /// Test the property 'FederalState'
        /// </summary>
        [Test]
        public void FederalStateTest()
        {
            // TODO unit test for the property 'FederalState'
        }
        /// <summary>
        /// Test the property 'FederalState2'
        /// </summary>
        [Test]
        public void FederalState2Test()
        {
            // TODO unit test for the property 'FederalState2'
        }
        /// <summary>
        /// Test the property 'FederalState3'
        /// </summary>
        [Test]
        public void FederalState3Test()
        {
            // TODO unit test for the property 'FederalState3'
        }
        /// <summary>
        /// Test the property 'FederalState4'
        /// </summary>
        [Test]
        public void FederalState4Test()
        {
            // TODO unit test for the property 'FederalState4'
        }
        /// <summary>
        /// Test the property 'FederalState5'
        /// </summary>
        [Test]
        public void FederalState5Test()
        {
            // TODO unit test for the property 'FederalState5'
        }
        /// <summary>
        /// Test the property 'FederalState6'
        /// </summary>
        [Test]
        public void FederalState6Test()
        {
            // TODO unit test for the property 'FederalState6'
        }
        /// <summary>
        /// Test the property 'Street1'
        /// </summary>
        [Test]
        public void Street1Test()
        {
            // TODO unit test for the property 'Street1'
        }
        /// <summary>
        /// Test the property 'Street2'
        /// </summary>
        [Test]
        public void Street2Test()
        {
            // TODO unit test for the property 'Street2'
        }
        /// <summary>
        /// Test the property 'Street3'
        /// </summary>
        [Test]
        public void Street3Test()
        {
            // TODO unit test for the property 'Street3'
        }
        /// <summary>
        /// Test the property 'Street4'
        /// </summary>
        [Test]
        public void Street4Test()
        {
            // TODO unit test for the property 'Street4'
        }
        /// <summary>
        /// Test the property 'Street5'
        /// </summary>
        [Test]
        public void Street5Test()
        {
            // TODO unit test for the property 'Street5'
        }
        /// <summary>
        /// Test the property 'Street6'
        /// </summary>
        [Test]
        public void Street6Test()
        {
            // TODO unit test for the property 'Street6'
        }
        /// <summary>
        /// Test the property 'AddressExtra1'
        /// </summary>
        [Test]
        public void AddressExtra1Test()
        {
            // TODO unit test for the property 'AddressExtra1'
        }
        /// <summary>
        /// Test the property 'AddressExtra2'
        /// </summary>
        [Test]
        public void AddressExtra2Test()
        {
            // TODO unit test for the property 'AddressExtra2'
        }
        /// <summary>
        /// Test the property 'AddressExtra3'
        /// </summary>
        [Test]
        public void AddressExtra3Test()
        {
            // TODO unit test for the property 'AddressExtra3'
        }
        /// <summary>
        /// Test the property 'AddressExtra4'
        /// </summary>
        [Test]
        public void AddressExtra4Test()
        {
            // TODO unit test for the property 'AddressExtra4'
        }
        /// <summary>
        /// Test the property 'AddressExtra5'
        /// </summary>
        [Test]
        public void AddressExtra5Test()
        {
            // TODO unit test for the property 'AddressExtra5'
        }
        /// <summary>
        /// Test the property 'AddressExtra6'
        /// </summary>
        [Test]
        public void AddressExtra6Test()
        {
            // TODO unit test for the property 'AddressExtra6'
        }
        /// <summary>
        /// Test the property 'City1'
        /// </summary>
        [Test]
        public void City1Test()
        {
            // TODO unit test for the property 'City1'
        }
        /// <summary>
        /// Test the property 'City2'
        /// </summary>
        [Test]
        public void City2Test()
        {
            // TODO unit test for the property 'City2'
        }
        /// <summary>
        /// Test the property 'City3'
        /// </summary>
        [Test]
        public void City3Test()
        {
            // TODO unit test for the property 'City3'
        }
        /// <summary>
        /// Test the property 'City4'
        /// </summary>
        [Test]
        public void City4Test()
        {
            // TODO unit test for the property 'City4'
        }
        /// <summary>
        /// Test the property 'City5'
        /// </summary>
        [Test]
        public void City5Test()
        {
            // TODO unit test for the property 'City5'
        }
        /// <summary>
        /// Test the property 'City6'
        /// </summary>
        [Test]
        public void City6Test()
        {
            // TODO unit test for the property 'City6'
        }
        /// <summary>
        /// Test the property 'Postcode1'
        /// </summary>
        [Test]
        public void Postcode1Test()
        {
            // TODO unit test for the property 'Postcode1'
        }
        /// <summary>
        /// Test the property 'Postcode2'
        /// </summary>
        [Test]
        public void Postcode2Test()
        {
            // TODO unit test for the property 'Postcode2'
        }
        /// <summary>
        /// Test the property 'Postcode3'
        /// </summary>
        [Test]
        public void Postcode3Test()
        {
            // TODO unit test for the property 'Postcode3'
        }
        /// <summary>
        /// Test the property 'Postcode4'
        /// </summary>
        [Test]
        public void Postcode4Test()
        {
            // TODO unit test for the property 'Postcode4'
        }
        /// <summary>
        /// Test the property 'Postcode5'
        /// </summary>
        [Test]
        public void Postcode5Test()
        {
            // TODO unit test for the property 'Postcode5'
        }
        /// <summary>
        /// Test the property 'Postcode6'
        /// </summary>
        [Test]
        public void Postcode6Test()
        {
            // TODO unit test for the property 'Postcode6'
        }
        /// <summary>
        /// Test the property 'Country1'
        /// </summary>
        [Test]
        public void Country1Test()
        {
            // TODO unit test for the property 'Country1'
        }
        /// <summary>
        /// Test the property 'Country2'
        /// </summary>
        [Test]
        public void Country2Test()
        {
            // TODO unit test for the property 'Country2'
        }
        /// <summary>
        /// Test the property 'Country3'
        /// </summary>
        [Test]
        public void Country3Test()
        {
            // TODO unit test for the property 'Country3'
        }
        /// <summary>
        /// Test the property 'Country4'
        /// </summary>
        [Test]
        public void Country4Test()
        {
            // TODO unit test for the property 'Country4'
        }
        /// <summary>
        /// Test the property 'Country5'
        /// </summary>
        [Test]
        public void Country5Test()
        {
            // TODO unit test for the property 'Country5'
        }
        /// <summary>
        /// Test the property 'Country6'
        /// </summary>
        [Test]
        public void Country6Test()
        {
            // TODO unit test for the property 'Country6'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Email2'
        /// </summary>
        [Test]
        public void Email2Test()
        {
            // TODO unit test for the property 'Email2'
        }
        /// <summary>
        /// Test the property 'Email3'
        /// </summary>
        [Test]
        public void Email3Test()
        {
            // TODO unit test for the property 'Email3'
        }
        /// <summary>
        /// Test the property 'Email4'
        /// </summary>
        [Test]
        public void Email4Test()
        {
            // TODO unit test for the property 'Email4'
        }
        /// <summary>
        /// Test the property 'Email5'
        /// </summary>
        [Test]
        public void Email5Test()
        {
            // TODO unit test for the property 'Email5'
        }
        /// <summary>
        /// Test the property 'Email6'
        /// </summary>
        [Test]
        public void Email6Test()
        {
            // TODO unit test for the property 'Email6'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'Phone2'
        /// </summary>
        [Test]
        public void Phone2Test()
        {
            // TODO unit test for the property 'Phone2'
        }
        /// <summary>
        /// Test the property 'Phone3'
        /// </summary>
        [Test]
        public void Phone3Test()
        {
            // TODO unit test for the property 'Phone3'
        }
        /// <summary>
        /// Test the property 'Phone4'
        /// </summary>
        [Test]
        public void Phone4Test()
        {
            // TODO unit test for the property 'Phone4'
        }
        /// <summary>
        /// Test the property 'Phone5'
        /// </summary>
        [Test]
        public void Phone5Test()
        {
            // TODO unit test for the property 'Phone5'
        }
        /// <summary>
        /// Test the property 'Phone6'
        /// </summary>
        [Test]
        public void Phone6Test()
        {
            // TODO unit test for the property 'Phone6'
        }
        /// <summary>
        /// Test the property 'Mobile'
        /// </summary>
        [Test]
        public void MobileTest()
        {
            // TODO unit test for the property 'Mobile'
        }
        /// <summary>
        /// Test the property 'Mobile2'
        /// </summary>
        [Test]
        public void Mobile2Test()
        {
            // TODO unit test for the property 'Mobile2'
        }
        /// <summary>
        /// Test the property 'Mobile3'
        /// </summary>
        [Test]
        public void Mobile3Test()
        {
            // TODO unit test for the property 'Mobile3'
        }
        /// <summary>
        /// Test the property 'Mobile4'
        /// </summary>
        [Test]
        public void Mobile4Test()
        {
            // TODO unit test for the property 'Mobile4'
        }
        /// <summary>
        /// Test the property 'Mobile5'
        /// </summary>
        [Test]
        public void Mobile5Test()
        {
            // TODO unit test for the property 'Mobile5'
        }
        /// <summary>
        /// Test the property 'Mobile6'
        /// </summary>
        [Test]
        public void Mobile6Test()
        {
            // TODO unit test for the property 'Mobile6'
        }
        /// <summary>
        /// Test the property 'Fax'
        /// </summary>
        [Test]
        public void FaxTest()
        {
            // TODO unit test for the property 'Fax'
        }
        /// <summary>
        /// Test the property 'Fax2'
        /// </summary>
        [Test]
        public void Fax2Test()
        {
            // TODO unit test for the property 'Fax2'
        }
        /// <summary>
        /// Test the property 'Fax3'
        /// </summary>
        [Test]
        public void Fax3Test()
        {
            // TODO unit test for the property 'Fax3'
        }
        /// <summary>
        /// Test the property 'Fax4'
        /// </summary>
        [Test]
        public void Fax4Test()
        {
            // TODO unit test for the property 'Fax4'
        }
        /// <summary>
        /// Test the property 'Fax5'
        /// </summary>
        [Test]
        public void Fax5Test()
        {
            // TODO unit test for the property 'Fax5'
        }
        /// <summary>
        /// Test the property 'Fax6'
        /// </summary>
        [Test]
        public void Fax6Test()
        {
            // TODO unit test for the property 'Fax6'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Test]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Test]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'PositionReplacement'
        /// </summary>
        [Test]
        public void PositionReplacementTest()
        {
            // TODO unit test for the property 'PositionReplacement'
        }
        /// <summary>
        /// Test the property 'Department'
        /// </summary>
        [Test]
        public void DepartmentTest()
        {
            // TODO unit test for the property 'Department'
        }
        /// <summary>
        /// Test the property 'Industry'
        /// </summary>
        [Test]
        public void IndustryTest()
        {
            // TODO unit test for the property 'Industry'
        }
        /// <summary>
        /// Test the property 'CustomerNumber'
        /// </summary>
        [Test]
        public void CustomerNumberTest()
        {
            // TODO unit test for the property 'CustomerNumber'
        }
        /// <summary>
        /// Test the property 'LegacyNumber'
        /// </summary>
        [Test]
        public void LegacyNumberTest()
        {
            // TODO unit test for the property 'LegacyNumber'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Test]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'Website'
        /// </summary>
        [Test]
        public void WebsiteTest()
        {
            // TODO unit test for the property 'Website'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'VatId'
        /// </summary>
        [Test]
        public void VatIdTest()
        {
            // TODO unit test for the property 'VatId'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'CustomFields'
        /// </summary>
        [Test]
        public void CustomFieldsTest()
        {
            // TODO unit test for the property 'CustomFields'
        }
        /// <summary>
        /// Test the property 'Employers'
        /// </summary>
        [Test]
        public void EmployersTest()
        {
            // TODO unit test for the property 'Employers'
        }
        /// <summary>
        /// Test the property 'DeliveryTermIncoterm'
        /// </summary>
        [Test]
        public void DeliveryTermIncotermTest()
        {
            // TODO unit test for the property 'DeliveryTermIncoterm'
        }
        /// <summary>
        /// Test the property 'DeliveryTermIncotermLocation'
        /// </summary>
        [Test]
        public void DeliveryTermIncotermLocationTest()
        {
            // TODO unit test for the property 'DeliveryTermIncotermLocation'
        }
        /// <summary>
        /// Test the property 'OwnerUid'
        /// </summary>
        [Test]
        public void OwnerUidTest()
        {
            // TODO unit test for the property 'OwnerUid'
        }
        /// <summary>
        /// Test the property 'PermissionType'
        /// </summary>
        [Test]
        public void PermissionTypeTest()
        {
            // TODO unit test for the property 'PermissionType'
        }
        /// <summary>
        /// Test the property 'ReadPermissionProfiles'
        /// </summary>
        [Test]
        public void ReadPermissionProfilesTest()
        {
            // TODO unit test for the property 'ReadPermissionProfiles'
        }
        /// <summary>
        /// Test the property 'ReadPermissionLogins'
        /// </summary>
        [Test]
        public void ReadPermissionLoginsTest()
        {
            // TODO unit test for the property 'ReadPermissionLogins'
        }
        /// <summary>
        /// Test the property 'WritePermissionProfiles'
        /// </summary>
        [Test]
        public void WritePermissionProfilesTest()
        {
            // TODO unit test for the property 'WritePermissionProfiles'
        }
        /// <summary>
        /// Test the property 'WritePermissionLogins'
        /// </summary>
        [Test]
        public void WritePermissionLoginsTest()
        {
            // TODO unit test for the property 'WritePermissionLogins'
        }

    }

}
