// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CompuMaster.Scopevisio.OpenScopeApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Account
    {
        /// <summary>
        /// Initializes a new instance of the Account class.
        /// </summary>
        public Account() { }

        /// <summary>
        /// Initializes a new instance of the Account class.
        /// </summary>
        public Account(string accountNumber = default(string))
        {
            AccountNumber = accountNumber;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accountNumber")]
        public string AccountNumber { get; set; }

    }
}
