// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CompuMaster.Scopevisio.OpenApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class BankStatementForm
    {
        /// <summary>
        /// Initializes a new instance of the BankStatementForm class.
        /// </summary>
        public BankStatementForm() { }

        /// <summary>
        /// Initializes a new instance of the BankStatementForm class.
        /// </summary>
        public BankStatementForm(string data = default(string))
        {
            Data = data;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "data")]
        public string Data { get; set; }

    }
}
