// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CompuMaster.Scopevisio.OpenApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class BlogEntryForm
    {
        /// <summary>
        /// Initializes a new instance of the BlogEntryForm class.
        /// </summary>
        public BlogEntryForm() { }

        /// <summary>
        /// Initializes a new instance of the BlogEntryForm class.
        /// </summary>
        public BlogEntryForm(string category = default(string), string body = default(string))
        {
            Category = category;
            Body = body;
        }

        /// <summary>
        /// category (Kommentar-Typ/Komentarart), default value is "Notiz" .
        /// Possible values include: 'Notiz', 'Anruf', 'Besprechung',
        /// 'Vertrag', 'E-mail'
        /// </summary>
        [JsonProperty(PropertyName = "category")]
        public string Category { get; set; }

        /// <summary>
        /// body (Kommentar)
        /// </summary>
        [JsonProperty(PropertyName = "body")]
        public string Body { get; set; }

    }
}
