// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CompuMaster.Scopevisio.OpenApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class OutgoingInvoiceImportResult
    {
        /// <summary>
        /// Initializes a new instance of the OutgoingInvoiceImportResult
        /// class.
        /// </summary>
        public OutgoingInvoiceImportResult() { }

        /// <summary>
        /// Initializes a new instance of the OutgoingInvoiceImportResult
        /// class.
        /// </summary>
        public OutgoingInvoiceImportResult(string message = default(string), IList<OutgoingInvoice> invoices = default(IList<OutgoingInvoice>), IList<Account> customers = default(IList<Account>), IList<Account> vendors = default(IList<Account>))
        {
            Message = message;
            Invoices = invoices;
            Customers = customers;
            Vendors = vendors;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "invoices")]
        public IList<OutgoingInvoice> Invoices { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customers")]
        public IList<Account> Customers { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "vendors")]
        public IList<Account> Vendors { get; set; }

    }
}
