// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CompuMaster.Scopevisio.OpenApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Mandatory if creating new outgoing invoice documents.
    /// </summary>
    public partial class Positionsform
    {
        /// <summary>
        /// Initializes a new instance of the Positionsform class.
        /// </summary>
        public Positionsform() { }

        /// <summary>
        /// Initializes a new instance of the Positionsform class.
        /// </summary>
        public Positionsform(IList<OutgoingInvoicePositionForm> positions, bool? copyProductsToPositions = default(bool?))
        {
            CopyProductsToPositions = copyProductsToPositions;
            Positions = positions;
        }

        /// <summary>
        /// Set to true if you want to use the existing products to create the
        /// positions. The product values are used only if the user has not
        /// provided values himself. E.g. if the singleAmount has been
        /// provided in the request body, the singleAmount from product is
        /// not used.
        /// </summary>
        [JsonProperty(PropertyName = "copyProductsToPositions")]
        public bool? CopyProductsToPositions { get; set; }

        /// <summary>
        /// positionsForm. Positions for outgoing invoice
        /// </summary>
        [JsonProperty(PropertyName = "positions")]
        public IList<OutgoingInvoicePositionForm> Positions { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Positions == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Positions");
            }
        }
    }
}
