// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CompuMaster.Scopevisio.OpenScopeApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Postings
    {
        /// <summary>
        /// Initializes a new instance of the Postings class.
        /// </summary>
        public Postings() { }

        /// <summary>
        /// Initializes a new instance of the Postings class.
        /// </summary>
        public Postings(bool? adjustVatKey = default(bool?), bool? autoCreateTax = default(bool?), IList<PostingRow> rows = default(IList<PostingRow>))
        {
            AdjustVatKey = adjustVatKey;
            AutoCreateTax = autoCreateTax;
            Rows = rows;
        }

        /// <summary>
        /// Replace the VAT key in the given rows with the vat key from the
        /// Scopevisio chart of accounts for this account.
        /// </summary>
        [JsonProperty(PropertyName = "adjustVatKey")]
        public bool? AdjustVatKey { get; set; }

        /// <summary>
        /// Create automatically tax posting rows. In this case an extra row
        /// for the tax posting is not needed.
        /// </summary>
        [JsonProperty(PropertyName = "autoCreateTax")]
        public bool? AutoCreateTax { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rows")]
        public IList<PostingRow> Rows { get; set; }

    }
}
