// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CompuMaster.Scopevisio.OpenApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class RevenueStatementAccountsForm
    {
        /// <summary>
        /// Initializes a new instance of the RevenueStatementAccountsForm
        /// class.
        /// </summary>
        public RevenueStatementAccountsForm() { }

        /// <summary>
        /// Initializes a new instance of the RevenueStatementAccountsForm
        /// class.
        /// </summary>
        public RevenueStatementAccountsForm(IList<RevenueStatementAccountRow> rows = default(IList<RevenueStatementAccountRow>))
        {
            Rows = rows;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rows")]
        public IList<RevenueStatementAccountRow> Rows { get; set; }

    }
}
