/* 
 * Scopevisio OpenScope REST API
 *
 * <p>This is an interactive API reference for the Scopevisio REST API.</p><p>Below you will see the main sections of the API. Click each section in order to see the endpoints that are available in that category and use the 'Try it out' button to make API calls.</p><p>For endpoints that require authentication you can click the lock symbol in the top right of the endpoint description, which will take you to a login form.</p><h3>Authentication</h3><p>In order to use the \"Try it out\" function in Swagger you need your own Scopevisio account. If you have not set up a Scopevisio user account already you can do so <a href='https://www.scopevisio.com' target='_blank'>here</a>.</p><h3>Example Application</h3><p>We also have an example application you can reach <a href='../browser/index.html'> here </a>. Usage requires a Scopevisio account.</p><h3>Search Documentation</h3><p>Our documentation regarding <a href='../browser/index.html#!/searchscope'>search specification and paging  </a>.</p><h3>General Documentation</h3><p>Our general documentation can be found <a href='../browser/index.html#!/documentation'> here </a>.</p>
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@scopevisio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing CreditForm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreditFormTests
    {
        // TODO uncomment below to declare an instance variable for CreditForm
        //private CreditForm instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreditForm
            //instance = new CreditForm();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreditForm
        /// </summary>
        [Test]
        public void CreditFormInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CreditForm
            //Assert.IsInstanceOf(typeof(CreditForm), instance);
        }


        /// <summary>
        /// Test the property 'ProjectId'
        /// </summary>
        [Test]
        public void ProjectIdTest()
        {
            // TODO unit test for the property 'ProjectId'
        }
        /// <summary>
        /// Test the property 'CustomerContactId'
        /// </summary>
        [Test]
        public void CustomerContactIdTest()
        {
            // TODO unit test for the property 'CustomerContactId'
        }
        /// <summary>
        /// Test the property 'CustomerContactName'
        /// </summary>
        [Test]
        public void CustomerContactNameTest()
        {
            // TODO unit test for the property 'CustomerContactName'
        }
        /// <summary>
        /// Test the property 'CustomerContactCustomerNumber'
        /// </summary>
        [Test]
        public void CustomerContactCustomerNumberTest()
        {
            // TODO unit test for the property 'CustomerContactCustomerNumber'
        }
        /// <summary>
        /// Test the property 'CustomerPersonalAccountId'
        /// </summary>
        [Test]
        public void CustomerPersonalAccountIdTest()
        {
            // TODO unit test for the property 'CustomerPersonalAccountId'
        }
        /// <summary>
        /// Test the property 'CustomerPersonalAccountNumber'
        /// </summary>
        [Test]
        public void CustomerPersonalAccountNumberTest()
        {
            // TODO unit test for the property 'CustomerPersonalAccountNumber'
        }
        /// <summary>
        /// Test the property 'CustomerPersonalAccountName'
        /// </summary>
        [Test]
        public void CustomerPersonalAccountNameTest()
        {
            // TODO unit test for the property 'CustomerPersonalAccountName'
        }
        /// <summary>
        /// Test the property 'CustomerPersonalAccountExternalNumber'
        /// </summary>
        [Test]
        public void CustomerPersonalAccountExternalNumberTest()
        {
            // TODO unit test for the property 'CustomerPersonalAccountExternalNumber'
        }
        /// <summary>
        /// Test the property 'CustomerName'
        /// </summary>
        [Test]
        public void CustomerNameTest()
        {
            // TODO unit test for the property 'CustomerName'
        }
        /// <summary>
        /// Test the property 'CustomerNumber'
        /// </summary>
        [Test]
        public void CustomerNumberTest()
        {
            // TODO unit test for the property 'CustomerNumber'
        }
        /// <summary>
        /// Test the property 'CustomerNameExtra'
        /// </summary>
        [Test]
        public void CustomerNameExtraTest()
        {
            // TODO unit test for the property 'CustomerNameExtra'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'CustomerContactPerson'
        /// </summary>
        [Test]
        public void CustomerContactPersonTest()
        {
            // TODO unit test for the property 'CustomerContactPerson'
        }
        /// <summary>
        /// Test the property 'DocumentDate'
        /// </summary>
        [Test]
        public void DocumentDateTest()
        {
            // TODO unit test for the property 'DocumentDate'
        }
        /// <summary>
        /// Test the property 'DocumentNumber'
        /// </summary>
        [Test]
        public void DocumentNumberTest()
        {
            // TODO unit test for the property 'DocumentNumber'
        }
        /// <summary>
        /// Test the property 'OurContactPerson'
        /// </summary>
        [Test]
        public void OurContactPersonTest()
        {
            // TODO unit test for the property 'OurContactPerson'
        }
        /// <summary>
        /// Test the property 'DeliveryType'
        /// </summary>
        [Test]
        public void DeliveryTypeTest()
        {
            // TODO unit test for the property 'DeliveryType'
        }
        /// <summary>
        /// Test the property 'DeliveryCosts'
        /// </summary>
        [Test]
        public void DeliveryCostsTest()
        {
            // TODO unit test for the property 'DeliveryCosts'
        }
        /// <summary>
        /// Test the property 'CashOnDelivery'
        /// </summary>
        [Test]
        public void CashOnDeliveryTest()
        {
            // TODO unit test for the property 'CashOnDelivery'
        }
        /// <summary>
        /// Test the property 'TextTitle'
        /// </summary>
        [Test]
        public void TextTitleTest()
        {
            // TODO unit test for the property 'TextTitle'
        }
        /// <summary>
        /// Test the property 'TextSubTitle'
        /// </summary>
        [Test]
        public void TextSubTitleTest()
        {
            // TODO unit test for the property 'TextSubTitle'
        }
        /// <summary>
        /// Test the property 'TextIntro'
        /// </summary>
        [Test]
        public void TextIntroTest()
        {
            // TODO unit test for the property 'TextIntro'
        }
        /// <summary>
        /// Test the property 'TextExtro'
        /// </summary>
        [Test]
        public void TextExtroTest()
        {
            // TODO unit test for the property 'TextExtro'
        }
        /// <summary>
        /// Test the property 'SelectedAddress'
        /// </summary>
        [Test]
        public void SelectedAddressTest()
        {
            // TODO unit test for the property 'SelectedAddress'
        }
        /// <summary>
        /// Test the property 'OtherAddress'
        /// </summary>
        [Test]
        public void OtherAddressTest()
        {
            // TODO unit test for the property 'OtherAddress'
        }
        /// <summary>
        /// Test the property 'Gross'
        /// </summary>
        [Test]
        public void GrossTest()
        {
            // TODO unit test for the property 'Gross'
        }
        /// <summary>
        /// Test the property 'PermissionType'
        /// </summary>
        [Test]
        public void PermissionTypeTest()
        {
            // TODO unit test for the property 'PermissionType'
        }
        /// <summary>
        /// Test the property 'ReadPermissionProfiles'
        /// </summary>
        [Test]
        public void ReadPermissionProfilesTest()
        {
            // TODO unit test for the property 'ReadPermissionProfiles'
        }
        /// <summary>
        /// Test the property 'ReadPermissionLogins'
        /// </summary>
        [Test]
        public void ReadPermissionLoginsTest()
        {
            // TODO unit test for the property 'ReadPermissionLogins'
        }
        /// <summary>
        /// Test the property 'WritePermissionProfiles'
        /// </summary>
        [Test]
        public void WritePermissionProfilesTest()
        {
            // TODO unit test for the property 'WritePermissionProfiles'
        }
        /// <summary>
        /// Test the property 'WritePermissionLogins'
        /// </summary>
        [Test]
        public void WritePermissionLoginsTest()
        {
            // TODO unit test for the property 'WritePermissionLogins'
        }
        /// <summary>
        /// Test the property 'CustomFields'
        /// </summary>
        [Test]
        public void CustomFieldsTest()
        {
            // TODO unit test for the property 'CustomFields'
        }
        /// <summary>
        /// Test the property 'PositionsForm'
        /// </summary>
        [Test]
        public void PositionsFormTest()
        {
            // TODO unit test for the property 'PositionsForm'
        }
        /// <summary>
        /// Test the property 'OrderNumber'
        /// </summary>
        [Test]
        public void OrderNumberTest()
        {
            // TODO unit test for the property 'OrderNumber'
        }
        /// <summary>
        /// Test the property 'ZoneNumber'
        /// </summary>
        [Test]
        public void ZoneNumberTest()
        {
            // TODO unit test for the property 'ZoneNumber'
        }
        /// <summary>
        /// Test the property 'StateName'
        /// </summary>
        [Test]
        public void StateNameTest()
        {
            // TODO unit test for the property 'StateName'
        }
        /// <summary>
        /// Test the property 'PostingDate'
        /// </summary>
        [Test]
        public void PostingDateTest()
        {
            // TODO unit test for the property 'PostingDate'
        }
        /// <summary>
        /// Test the property 'DocumentText'
        /// </summary>
        [Test]
        public void DocumentTextTest()
        {
            // TODO unit test for the property 'DocumentText'
        }
        /// <summary>
        /// Test the property 'Locale'
        /// </summary>
        [Test]
        public void LocaleTest()
        {
            // TODO unit test for the property 'Locale'
        }

    }

}
